// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxmmRbq_mCH_u5S3VTNhkhwD_pTNcqLfo',
    appId: '1:256051325877:web:7d430d3332e65a429a07fc',
    messagingSenderId: '256051325877',
    projectId: 'tchadopportunite-2dde0',
    authDomain: 'tchadopportunite-2dde0.firebaseapp.com',
    storageBucket: 'tchadopportunite-2dde0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP_QiMipnhlRzSuDw9RFGKfG-vgZT9Tqc',
    appId: '1:256051325877:android:2b1a8211989e00ed9a07fc',
    messagingSenderId: '256051325877',
    projectId: 'tchadopportunite-2dde0',
    storageBucket: 'tchadopportunite-2dde0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAATXg8Hq7EXLWUK2TMIXAmS55j9m5DWSE',
    appId: '1:256051325877:ios:0ba389018030d5029a07fc',
    messagingSenderId: '256051325877',
    projectId: 'tchadopportunite-2dde0',
    storageBucket: 'tchadopportunite-2dde0.firebasestorage.app',
    iosClientId: '256051325877-6bbh21a41vuaucba2tf6easr7kia6i0r.apps.googleusercontent.com',
    iosBundleId: 'com.tchadopportunite.tchadopportunite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAATXg8Hq7EXLWUK2TMIXAmS55j9m5DWSE',
    appId: '1:256051325877:ios:0ba389018030d5029a07fc',
    messagingSenderId: '256051325877',
    projectId: 'tchadopportunite-2dde0',
    storageBucket: 'tchadopportunite-2dde0.firebasestorage.app',
    iosClientId: '256051325877-6bbh21a41vuaucba2tf6easr7kia6i0r.apps.googleusercontent.com',
    iosBundleId: 'com.tchadopportunite.tchadopportunite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxmmRbq_mCH_u5S3VTNhkhwD_pTNcqLfo',
    appId: '1:256051325877:web:7f135dac9bbe8e089a07fc',
    messagingSenderId: '256051325877',
    projectId: 'tchadopportunite-2dde0',
    authDomain: 'tchadopportunite-2dde0.firebaseapp.com',
    storageBucket: 'tchadopportunite-2dde0.firebasestorage.app',
  );
}
